//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public byte[] FileData { get; set; }
        public string ImageMimeType { get; set; }
        public string Src { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
